name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build CMOCKA
      run: |
        wget https://cmocka.org/files/1.1/cmocka-1.1.5.tar.xz
        tar -xf cmocka-1.1.5.tar.xz
        cd cmocka-1.1.5/
        mkdir build
        cd build/
        cmake -DCMAKE_INSTALL_PREFIX=/user ..
        sudo make install
        cd ../../
    - name: Install dependencies
      run: sudo apt install libsigsegv-dev libexpat1-dev gcc-10 g++-10
    - name: Update generated configuration files
      run: autoreconf -vi
    - name: configure
      run: |
        export PKG_CONFIG_PATH=/user/lib/pkgconfig
        ./configure
    - name: make
      run: make
      shell: bash
    - name: make check
      run: LD_LIBRARY_PATH=/user/lib make check
    - name: upload tests results
      uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: tests
        path: tests
